blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share', views.post_share, name='share_post'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from collections.abc import MutableMapping
from typing import Any
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    class PublishedManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status=Post.Status.PUBLISHED)

    class Status(models.TextChoices):
        DRAFT = 'DF', 'DRAFT'
        PUBLISHED = 'PB', 'PUBLISHED'
    
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    objects = models.Manager()
    published = PublishedManager()
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year, self.publish.month, self.publish.day, self.slug])
    

blog/forms.py
from django import forms

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)    
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage,\
    PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm
from django.core.mail import send_mail
from django.conf import settings

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} recommends you to read "\
                f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n"\
                f"{cd['name']}'s comments: {cd['comments']}"
            send_mail(subject, message, settings.EMAIL_HOST_USER, [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

def post_detail(request, day, month, year, post):
    post = get_object_or_404(Post,
                            status=Post.Status.PUBLISHED,
                            slug=post,
                            publish__year=year,
                            publish__month=month,
                            publish__day=day)
    return render(request, 'blog/post/detail.html', {'post':post})

blog/templates/blog/base.html
{% load static %}
<html>
  <head>
    <link rel="stylesheet" href="{% static 'src/styles.css' %}" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>     
    <div>{% block content %} {% endblock content %}</div>
  </body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block content %}
<div class="mx-auto w-1/2">
<h1 class="text-2xl my-5">{{post.title}}</h1>
<p class="text-gray-500">Published {{post.publish}} by {{post.author}}</p>

<p class="my-5">{{post.body|linebreaks}}</p>
<p>
    <a class="inline-block my-5 bg-black text-white px-4 py-2 rounded-xl" href="{% url 'blog:share_post' post.id %}">Share this post</a>
</p>
</div>
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %} 
{% block title %}My Blog{% endblock %}
{% block content %}
<div class="mx-auto w-3/4">
    <h1 class="mt-5 border-b-2 pb-3 text-lg">My Blog</h1>
    {% for post in posts %}   
    <div class="w-full mx-auto max-w-md px-8 py-4 mt-16 bg-white rounded-lg shadow-lg ">
        <h2 class="mt-2 text-xl font-semibold text-gray-800  md:mt-0">{{post.title}}</h2>

        <div class="text-sm mt-2 text-gray-400"> Published {{post.publish}} by {{post.author}}</div>
        <p class="mt-2 text-sm text-gray-600">
            {{post.body|truncatechars:30|linebreaks}}
        </p>
        <div class="flex justify-end mt-5">
            <a href="{{ post.get_absolute_url }}" class="text-lg font-medium text-blue-600 " tabindex="0" role="link">View more</a>
        </div>
    </div>
    {% endfor %} 
    {% include "pagination.html" with page=page_obj %}
</div>
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block content %}
<div class="w-1/2 pt-5 mx-auto">
{% if sent %}
    <h1>Email sent successfully</h1>
    <p>"{{post.title}}" was successfully sent to {{form.cleaned_data.to}}.</p>
{% else %}
    <h1 class="text-xl my-2">Share "{{post.title}}" by email</h1>
    <form method="post">{% csrf_token %}
        {{form.as_p}}
        <input class="bg-black rounded-md text-white px-3 py-2" type="submit" value="Send e-mail">
    </form>
{% endif %}
</div>
{% endblock %}

blog/templates/pagination.html
<nav class="w-1/2 mx-auto my-5">
    <ul class="inline-flex -space-x-px text-sm">
    {% if page.has_previous %}
    <li>
        <a href="?page={{page.previous_page_number}}" class="flex items-center justify-center px-3 h-8 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700">Previous</a>
      </li>
      {% else %}
      <li>
        <a class="flex items-center justify-center px-3 h-8 ml-0 leading-tight text-gray-300 bg-white border border-gray-300 rounded-l-lg ">Previous</a>
      </li>
    {% endif %}

      <li>
        <span class="flex items-center justify-center px-3 h-8 cursor-pointer leading-tight text-gray-500 bg-white border border-gray-300 ">Page {{page.number}} of {{page.paginator.num_pages}}</span>
      </li>
      {% if page.has_next %}
      <li>
        <a href="?page={{page.next_page_number}}" class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 ">Next</a>
      </li>
      {% else %}
      <li>
        <a class="flex items-center justify-center px-3 h-8 leading-tight text-gray-300 bg-white border border-gray-300 rounded-r-lg">Next</a>
      </li>
      {% endif %}
    </ul>
  </nav>